[package]
name = "opengl_app"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sdl2 = "0.35.2"
gl = "0.14.0"
cgmath = "0.18.0"
c_str_macro = "1.0.3"
